### ISSUE TITLE
[Question] Running nsh with ReactorController?

### ISSUE THREAD

**Issue by Sooperfish** [Kasra-G/ReactorController#11]
I was looking for a way to look at reactor statistics from my ae2 room, and I found [nsh](http://www.computercraft.info/forums2/index.php?/topic/6472-nsh-now-with-previous-session-resume/), a remote terminal program that lets you connect to a different computer. Is there any way I can run this? Even when I modify the script not to use startup so I can run nsh before the reactor, it won't let me connect.
Maybe a ReactorController companion script to connect to reactor monitors?

**Comment by Kasra-G** [comment]
Need to make a remote monitoring / controlling script

**Comment by Kasra-G** [comment]
Hey, so this is likely going to be shelved - remote control would be nice, but a bit of a niche use case considering for most, a wire modem setup is going to work fine.

A remote monitoring/controlling script is possible but I'd rather work on something that a lot of people would benefit from, like turbine support
