### ISSUE TITLE
Does not work via modem for BiggerReactors v0.6.0

### ISSUE THREAD

**Issue by Kaes3kuch3n** [Kasra-G/ReactorController#12]
I'm currently playing the UniversIO pack from CurseForge, which includes BiggerReactors v0.6.0. I've built a reactor with an advanced computer connected to the computer port of the reactor via wired modem, but the program doesn't seem to recognize the reactor that way. The screen just stays blank.

It seems to work fine when the computer is sitting right next to the port block of the reactor though.

Great program by the way, thanks for publishing it :)

**Comment by Kasra-G** [comment]
Thanks for reporting, ill take a look at this. Sorry for 6 months late, lol

**Comment by Kasra-G** [comment]
Hey, I am unable to reproduce this. Make sure to right click the modems when you attach it to the monitor/computer port
