### ISSUE TITLE
GUI seems broken

### ISSUE THREAD

**Issue by RedBloodCat** [Kasra-G/ReactorController#15]
Just started using it in ATM9, but it seems some part of the GUI is FUBAR. The program in it self works, its deploying the control rods and so on fine.

![image](https://github.com/user-attachments/assets/c0ca5264-9238-44ca-a916-b32c77c950fc)

**Comment by RedBloodCat** [comment]
Restart did not fix it, nor redownloading the program on a new computer, not rebuilding the whole computer network

**Comment by Bootscreen** [comment]
Looks like in default the temps and control level are disabled. build it 4 blocks high. than you can enable it

**Comment by RedBloodCat** [comment]
That fixed it, it should maybe be on by default tho
