### ISSUE TITLE
touchpoint.lua and reactorController.lua does not have a version variable

### ISSUE THREAD

**Issue by jason-vivid** [Kasra-G/ReactorController#18]
After running `pastebin run kSkwEchg`

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/cf0c3fcf-f685-4e5d-9181-edb8d72bf2d8">

**Comment by Kasra-G** [comment]
Fixed, this was due to a change in the pastebin API.

Unfortunately it can't be automatically fixed as the update script isn't versioned but wiping the computer and re-running the pastebin run command should fix.

**Comment by Kasra-G** [comment]
Fixed by #19 , as stated above, a wipe + reinstall is required for the fix
