### ISSUE TITLE
Server console spam when running

### ISSUE THREAD

**Issue by instinxx** [Kasra-G/ReactorController#3]
When running the script to control an Extreme Reactor in 1.18.1 the console spams the following:

[Server thread/ERROR]: Exception raised while running computer method setControlRodLevel on server thread : Invalid argument 1, valid range is 0 : 100

Using CC:Tweaked 1.18.1-1.100.2 and Extreme Reactors 1.18.1-2.0.38

Thanks for the script!

**Comment by Kasra-G** [comment]
Hmm, I'll do some testing. My initial thought is "that error is impossible" but we'll see. It's possible that a bug on my end has gone unnoticed or the Extreme reactors API changed.

**Comment by Kasra-G** [comment]
it looked like through some math magic, it was possible to get the control rod levels to go out of bounds. Rare but possible. Now it is impossible. Next time you load your CC computer it will download version 0.43 from pastebin. If it still says 0.42 then hold ctrl R to restart the computer and that should grab the latest version. Let me know if this works

**Comment by instinxx** [comment]
Thanks! That seems to have resolved the issue.
