### ISSUE TITLE
Is it possible to add an option which makes it run for turbines?

### ISSUE THREAD

**Issue by iCraft85** [Kasra-G/ReactorController#5]
Basically what the title says, was wondering if you would ever add an option where it runs for a turbine? and if you do decide add code for the turbine would it be possible to control multiple turbines together?

**Comment by Kasra-G** [comment]
Great idea, definitely something I would consider doing. Probably after my exams, if I got time, I'll hop on, clean up my code and see about adding some turbine support

**Comment by iCraft85** [comment]
ty and gl with ur exams :D

**Comment by Zonk1987** [comment]
Are there some hope that we get the feature in the near future? ☺️

**Comment by Kasra-G** [comment]
Closing, ill track support in #16 and eventually in a PR.

Maybe it can be a new years present for you all :)
