### ISSUE TITLE
Efficiency says "inf GRF/B"

### ISSUE THREAD

**Issue by denkisikinoneko** [Kasra-G/ReactorController#6]
![image](https://user-images.githubusercontent.com/31296383/164426552-1d91c3d0-c7ff-4609-8162-027c0c2133cf.png)
When fuel usage goes to zero (but still generating power), it says this.

**Comment by Kasra-G** [comment]
Thanks for making an issue! This is intended. If you're using 0 fuel and making power, then your efficiency (RF/Fuel) would be infinite.
